FROM nvidia/cuda:10.2-runtime-ubuntu18.04


RUN apt update && apt install -y git python3.7 python3-pip \
    && cd /usr/local/bin \
    && ln -nsf /usr/bin/python3.7 python \
    && python -m pip install --no-cache-dir --upgrade pip

RUN JINA_PIP_INSTALL_PERF=1 pip install jina==2.0.20

# setup the workspace
COPY . /workspace
WORKDIR /workspace

# install Jina and third-party requirements
RUN pip install -r gpu_requirements.txt

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]