FROM nvidia/cuda:11.3.1-cudnn8-runtime

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y python3.8 python3-pip git libgomp1 libglib2.0-0 libsm6 libxext6 libfontconfig1 libxrender1
RUN JINA_PIP_INSTALL_PERF=1 pip install --no-cache-dir jina==2.0.20

COPY requirements.txt gpu_requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /image_paddlehub/
WORKDIR /image_paddlehub

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
