FROM nvidia/cuda:11.3.1-cudnn8-runtime

RUN apt update && apt install -y python3.8 python3-pip git

COPY . ./tf_encoder/
WORKDIR ./tf_encoder

RUN pip install -r requirements.txt

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
