FROM nvidia/cuda:11.3.1-cudnn8-runtime

RUN apt update && apt install -y python3.8 python3-pip git
RUN JINA_PIP_INSTALL_PERF=1 pip install --no-cache-dir jina==2.0.20

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./tf_encoder/
WORKDIR ./tf_encoder

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
