FROM nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04

RUN apt update && apt install -y python3.8 python3-pip git
RUN JINA_PIP_INSTALL_PERF=1 pip install --no-cache-dir jina~=3

COPY gpu_requirements.txt gpu_requirements.txt
RUN pip install --no-cache-dir -r gpu_requirements.txt

COPY . /workdir/
WORKDIR /workdir

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]