FROM jinaai/jina:3-py37-perf

# install git
RUN apt-get -y update && apt-get install -y wget ffmpeg libsndfile-dev

# install requirements before copying the workspace
COPY gpu_requirements.txt gpu_requirements.txt
RUN pip install --upgrade pip
RUN pip install -r gpu_requirements.txt

# setup the workspace
COPY . /workdir
WORKDIR /workdir

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
