name: CI

on: [pull_request]

jobs:
  prep-testbed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: changed-files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - id: set-matrix
        run: bash scripts/get-all-test-paths.sh
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all }}
      - id: debug
        run: echo ${{ steps.set-matrix.outputs.matrix }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  linting:
    needs: [prep-testbed]
    runs-on: ubuntu-latest
    if: ${{ needs.prep-testbed.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        executor-path: ${{fromJson(needs.prep-testbed.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install requirements
        run: pip install black flake8 isort
      - name: Flake8 linting
        run: flake8 ${{ matrix.executor-path }}
      - name: Check imports using isort
        run: isort --check-only ${{ matrix.executor-path }}
      - name: Black check formatting
        run: black --check ${{ matrix.executor-path }}

  unit-tests:
    needs: [prep-testbed]
    runs-on: ubuntu-latest
    if: ${{ needs.prep-testbed.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        executor-path: ${{fromJson(needs.prep-testbed.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.executor-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Pre-test script
        run: |
          if [[ -f "tests/pre_test.sh" ]]; then
            bash tests/pre_test.sh; fi
      - name: Install latest stable 2.x jina version
        run: |
          JINA_VERSION=$(curl -L -s "https://pypi.org/pypi/jina/json" \
            |  jq  -r '.releases | keys | .[]
              | select(contains("dev") | not)
              | select(startswith("2."))' \
            | sort -V | tail -1)
          pip install git+https://github.com/jina-ai/jina.git@v${JINA_VERSION}
      - name: Install image normalizer
        run: pip install git+https://github.com/jina-ai/executor-normalizer
      - name: Python requirements
        run: pip install -r requirements.txt -r tests/requirements.txt
      - name: Create Dockerfile, if needed
        run: |
          if [[ ! -f "Dockerfile" ]]; then
            normalizer . --jina-version=2; fi
      - name: Run unit tests
        run: pytest -s -v -m "not gpu"
      # - name: Print image size
      #   run: |
      #     IMG_NAME=$(echo "${PWD##*/}" | tr '[:upper:]' '[:lower:]')
      #     docker inspect $IMG_NAME | jq '.[0].Size' | numfmt --to=iec --suffix=B

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # @@@@@@@ ⚠️ DEPRECATED ⚠️ @@@@@@@@@
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # This job should be removed once all executors are reformatted,
  # new way of testing docker files is directly with pytest, see
  # CONTRIBUTING.md in this repo

  docker-tests:
    needs: [prep-testbed]
    runs-on: ubuntu-latest
    if: ${{ needs.prep-testbed.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        executor-path: ${{fromJson(needs.prep-testbed.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: debug
        run: echo ${{ matrix.test-path }}
      - name: run docker tests
        run: |
          if [[ -f "${{ matrix.executor-path }}/Dockerfile" ]]; then
            bash ./scripts/test_docker.sh ${{ matrix.executor-path }}; fi

  # always run
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install requirements
        run: |
          pip install -r tests/requirements.txt
      - name: Run integration tests
        run: PYTHONPATH=. pytest -s -v tests/integration

  gpu-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - id: set-matrix
        run: bash scripts/get-gpu-executors.sh
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  gpu-tests:
    needs: [gpu-folders]
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      matrix:
        folder: ${{fromJson(needs.gpu-folders.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Pre-test script
        run: |
          if [[ -f "scripts/pre_test.sh" ]]; then
            bash scripts/pre_test.sh; fi
      - name: Install jina
        run: pip install git+https://github.com/jina-ai/jina/
      - name: Python requirements
        run: pip install -r requirements.txt -r tests/requirements.txt
      - name: Image name
        run: echo "IMAGE_NAME=$(echo "${PWD##*/}:gpu" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: build docker image
        run: docker build -t $IMAGE_NAME -f Dockerfile.gpu .
      - name: Print image size
        run: docker inspect $IMAGE_NAME | jq '.[0].Size' | numfmt --to=iec --suffix=B      
      - name: start container
        run: |
          docker run \
            --entrypoint "" \
            --name ${PWD##*/} \
            --gpus all \
            -d $IMAGE_NAME tail -F /dev/null
          echo "DOCKER_EXEC=docker exec ${PWD##*/}" >> $GITHUB_ENV
      - name: Run GPU tests in container
        run: |
          $DOCKER_EXEC pip install -r tests/requirements.txt
          $DOCKER_EXEC ls
          $DOCKER_EXEC pytest -s -v -m "gpu and not docker" tests/
      - name: Run test of GPU image
        run: pytest -s -v -m "gpu and docker"
      - name: stop container
        if: ${{ always() }}
        run: docker stop $(docker ps -a -q) && docker rm ${PWD##*/}
